<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

1. Subsetting refers to "select" an element 
2. Indexing refers to choosing a element
3. Slicing refers to choosing a range of elements
4. Masking refers to only allowing certain elements that meet a certain conditions to be seen.

In [6]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2dt = np_array_2d[:,0]
np_array_int = np_array_2dt.astype(int)
np_array_rem = np_array_int % 2
np_array_mask = np_array_rem > 0
for count,value in enumerate(np_array_mask):
    if value == True:
        print(np_array_2d[count,-1])


A
C
E
G
I


In [ ]:
list=[[66, 50, 57, -1, -1],[92, -1, 88, -1, -1], [75, -1, -1, 76, -1], [-1, 51, 87, -1, -1], [71, -1, 67, -1, 69]]
np_array = np.array(list)
np_array[np_array == 50] = 0
np_array[np_array > 50] = 1
print(np_array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
